#! /bin/sh

# sxhkd
pgrep -x sxhkd > /dev/null || sxhkd &

# Background
feh --bg-scale --no-xinerama "$HOME/.local/share/bg" &

# Polybar
$XDG_CONFIG_HOME/polybar/launch.sh &

# Network-Manager Applet
nm-applet &

# Hide Inactive Mouse
unclutter -b --timeout 3 &

# Monitors
if xrandr | grep "HDMI-2 disconnected" ; then
	bspc monitor 'eDP-1' -d I II III IV V VI VII VIII IX X
else
	xrandr --output 'eDP-1' --auto --output 'HDMI-2' --mode 2560x1080 --primary --right-of 'eDP-1'
	bspc monitor 'eDP-1' -d I II III IV
	bspc monitor 'HDMI-2' -d V VI VII VIII IX X
fi

# Window Settings
bspc config border_width         					4
bspc config window_gap          						30
bspc config split_ratio          					0.45
bspc config borderless_monocle   					true
bspc config gapless_monocle 							true

# Pointer Settings
bspc config pointer_follows_focus               true
bspc config focus_follows_pointer               true

## Remove all rules before a bspwm restart
bspc rule -r "*"

# App Window Rules
bspc rule -a KeePassXC state=floating follow=on rectangle=800x600+0+0

# Java applications window fix
wmname LG3D

# Run on startup
keepassxc
